<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4420.1017">
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </PackageReference>
  </ItemGroup>

</Project>
