<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ReportGenerator.CLI</RootNamespace>
    <AssemblyName>ReportGenerator.CLI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportGenerator.Services\ReportGenerator.Services.csproj" />
  </ItemGroup>

</Project>
