<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ReportGeneratorWPF</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportGenerator.Services\ReportGenerator.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo.png" />
    <Resource Include="logo.ico" />
  </ItemGroup>

</Project>
